### PR TITLE
Support derive, function-like proc-macros

### PR DESCRIPTION
**Pull request by mxxo**
Add support for custom derives and function-like procedural macros (#1)

@bbqsrc, please let me know if you'd prefer the CLI done another way. For now, I've added a new option "kind" to specify what kind of proc-macro to create. Attribute macros are the default.

**Attributes** 
```
$ cargo proc-macro new some-attr
```
or
```
$ cargo proc-macro new some-attr --kind=attribute
```
```
-- Created workspace with `some-attr` and `some-attr_macro` crates.

`some-attr` is the crate you should use in Rust projects. For example:

    use some_attr::some_attr;
    #[some_attr]
    fn some_compatible_element() { ... }

The testable logic for your macro lives in `some-attr_macro` and is a dependency of `some-attr`.
```
**Function-like**
```
$ cargo proc-macro new some-proc-macro --kind=function
-- Created workspace with `some-proc-macro` and `some-proc-macro_macro` crates.

`some-proc-macro` is the crate you should use in Rust projects. For example:

    use some_proc_macro::some_proc_macro;
    fn some_fn() {
        some_proc_macro!(...);
    }

The testable logic for your macro lives in `some-proc-macro_macro` and is a dependency of `some-proc-macro`.
```

**Custom derive**
```
$ cargo proc-macro new CoolDerive --kind=derive
-- Created workspace with `CoolDerive` and `CoolDerive_macro` crates.

`CoolDerive` is the crate you should use in Rust projects. For example:

    use CoolDerive::CoolDerive;
    #[derive(CoolDerive)]
    struct SomeStruct;

The testable logic for your macro lives in `CoolDerive_macro` and is a dependency of `CoolDerive`.
```
I am not completely satisfied with the derive output. It is tricky to get the correct crate name (kebab-case), crate name in code (snake_case) and struct name (CamelCase).  Ideally the above should be: 

```
$ cargo proc-macro new CoolDerive --kind=derive
-- Created workspace with `cool-derive` and `cool-derive_macro` crates.

`cool-derive` is the crate you should use in Rust projects. For example:

    use cool_derive::CoolDerive;
    #[derive(CoolDerive)]
    struct SomeStruct;

The testable logic for your macro lives in `cool-derive_macro` and is a dependency of `cool-derive`.
```

What do you think about adding, say,  [`heck`](https://docs.rs/heck/0.3.1/heck/) as a dependency to handle this?

### CODE REVIEW

**Comment by bbqsrc** [comment]
I add heck to basically everything, so I'm surprised it wasn't already included. By all means add it.

Pull request looks pretty solid. 😄👍

**Comment by mxxo** [comment]
Awesome, thank you :)

with b097a17 the derive output looks like: 
```
$ cargo proc-macro new CoolDerive --kind=derive
-- Created workspace with `cool-derive` and `cool-derive_macro` crates.

`cool-derive` is the crate you should use in Rust projects. For example:

    use cool_derive::CoolDerive;
    #[derive(CoolDerive)]
    struct SomeStruct;

The testable logic for your macro lives in `cool-derive_macro` and is a dependency of `cool-derive`.
```

**Comment by bbqsrc** [comment]
And merged. Great contribution, thanks again! If you want to slap your name in the authors, by all means send a PR for that.

**Comment by mxxo** [comment]
Sure! Thank you, that's very kind. Thanks also for integrating it.

**Pull request merged**
